---
version: 2
multicolumn: false
web-width: 300px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/reconstruction steps/reconstruction steps.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/1401/articles/416911/master/file/figures/reconstruction%20steps/reconstruction%20steps.png"
    folder_url: "/users/1401/articles/416911/master/folder/figures/reconstruction
      steps"
